server:
  port: 8080
#  parametrizar puerto
spring:
  main:
    allow-circular-references: true
  application:
    name: crm_db
  datasource:
    url: jdbc:mysql://${MYSQLHOST}:3306/${MYSQL_DATABASE}
    username: ${MYSQLUSER}
    password: ${MYSQLPASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
#    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
#      driver: com.mysql.cj.jdbc.Driver
      ddl-auto: none
      dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  security:
    debug: true
jwt:
  secret: MyCookieJar123
springdoc:
  swagger-ui:
    path: /crm_db.html
    operationsSorter: method
logging:
  level:
    org.springframework.security: DEBUG
    root: DEBUG
    org.hibernate.SQL: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n%ex"
